// Code generated by "stringer -type=batteryState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[batteryGood-0]
	_ = x[batteryPoor-1]
}

const _batteryState_name = "batteryGoodbatteryPoor"

var _batteryState_index = [...]uint8{0, 11, 22}

func (i batteryState) String() string {
	if i < 0 || i >= batteryState(len(_batteryState_index)-1) {
		return "batteryState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _batteryState_name[_batteryState_index[i]:_batteryState_index[i+1]]
}
