// Code generated by "stringer -type=blindsState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[bedroomBlindsStateClosed-0]
	_ = x[bedroomBlindsStateOpen-1]
}

const _blindsState_name = "bedroomBlindsStateClosedbedroomBlindsStateOpen"

var _blindsState_index = [...]uint8{0, 24, 46}

func (i blindsState) String() string {
	if i < 0 || i >= blindsState(len(_blindsState_index)-1) {
		return "blindsState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _blindsState_name[_blindsState_index[i]:_blindsState_index[i+1]]
}
