// Code generated by "stringer -type=doorState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[doorClosed-0]
	_ = x[doorOpen-1]
	_ = x[doorOpenLong-2]
}

const _doorState_name = "doorCloseddoorOpendoorOpenLong"

var _doorState_index = [...]uint8{0, 10, 18, 30}

func (i doorState) String() string {
	if i < 0 || i >= doorState(len(_doorState_index)-1) {
		return "doorState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _doorState_name[_doorState_index[i]:_doorState_index[i+1]]
}
