// Code generated by "stringer -type=homePresenceState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[presenceInitial-1]
	_ = x[presenceHome-2]
	_ = x[presenceAway-3]
}

const _homePresenceState_name = "presenceInitialpresenceHomepresenceAway"

var _homePresenceState_index = [...]uint8{0, 15, 27, 39}

func (i homePresenceState) String() string {
	i -= 1
	if i < 0 || i >= homePresenceState(len(_homePresenceState_index)-1) {
		return "homePresenceState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _homePresenceState_name[_homePresenceState_index[i]:_homePresenceState_index[i+1]]
}
