// Code generated by "stringer -type=kitchenAmpState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[kitchenAmpStateOff-0]
	_ = x[kitchenAmpStateOn-1]
}

const _kitchenAmpState_name = "kitchenAmpStateOffkitchenAmpStateOn"

var _kitchenAmpState_index = [...]uint8{0, 18, 35}

func (i kitchenAmpState) String() string {
	if i < 0 || i >= kitchenAmpState(len(_kitchenAmpState_index)-1) {
		return "kitchenAmpState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _kitchenAmpState_name[_kitchenAmpState_index[i]:_kitchenAmpState_index[i+1]]
}
