// Code generated by "stringer -type=kitchenAudioState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateKitchenAudioLocal-0]
	_ = x[stateKitchenAudioRemote-1]
}

const _kitchenAudioState_name = "stateKitchenAudioLocalstateKitchenAudioRemote"

var _kitchenAudioState_index = [...]uint8{0, 22, 45}

func (i kitchenAudioState) String() string {
	if i < 0 || i >= kitchenAudioState(len(_kitchenAudioState_index)-1) {
		return "kitchenAudioState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _kitchenAudioState_name[_kitchenAudioState_index[i]:_kitchenAudioState_index[i+1]]
}
