// Code generated by "stringer -type=livingroomFloorlamp"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateLivingroomFloorlampOff-0]
	_ = x[stateLivingroomFloorlampOn-1]
}

const _livingroomFloorlamp_name = "stateLivingroomFloorlampOffstateLivingroomFloorlampOn"

var _livingroomFloorlamp_index = [...]uint8{0, 27, 53}

func (i livingroomFloorlamp) String() string {
	if i < 0 || i >= livingroomFloorlamp(len(_livingroomFloorlamp_index)-1) {
		return "livingroomFloorlamp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _livingroomFloorlamp_name[_livingroomFloorlamp_index[i]:_livingroomFloorlamp_index[i+1]]
}
