// Code generated by "stringer -type=livingroomLamp"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateLivingroomFloorlampOff-0]
	_ = x[stateLivingroomFloorlampOn-1]
}

const _livingroomLamp_name = "stateLivingroomFloorlampOffstateLivingroomFloorlampOn"

var _livingroomLamp_index = [...]uint8{0, 27, 53}

func (i livingroomLamp) String() string {
	if i < 0 || i >= livingroomLamp(len(_livingroomLamp_index)-1) {
		return "livingroomLamp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _livingroomLamp_name[_livingroomLamp_index[i]:_livingroomLamp_index[i+1]]
}
