// Code generated by "stringer -type=livingroomWindowLamp"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateLivingroomWindowlampOff-0]
	_ = x[stateLivingroomWindowlampOn-1]
}

const _livingroomWindowLamp_name = "stateLivingroomWindowlampOffstateLivingroomWindowlampOn"

var _livingroomWindowLamp_index = [...]uint8{0, 28, 55}

func (i livingroomWindowLamp) String() string {
	if i < 0 || i >= livingroomWindowLamp(len(_livingroomWindowLamp_index)-1) {
		return "livingroomWindowLamp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _livingroomWindowLamp_name[_livingroomWindowLamp_index[i]:_livingroomWindowLamp_index[i+1]]
}
