// Code generated by "stringer -type=mpdState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mpdStateOff-0]
	_ = x[mpdStateOn-1]
}

const _mpdState_name = "mpdStateOffmpdStateOn"

var _mpdState_index = [...]uint8{0, 11, 21}

func (i mpdState) String() string {
	if i < 0 || i >= mpdState(len(_mpdState_index)-1) {
		return "mpdState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mpdState_name[_mpdState_index[i]:_mpdState_index[i+1]]
}
