// Code generated by "stringer -type=snapcastState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateSnapcastOff-0]
	_ = x[stateSnapcastOn-1]
}

const _snapcastState_name = "stateSnapcastOffstateSnapcastOn"

var _snapcastState_index = [...]uint8{0, 16, 31}

func (i snapcastState) String() string {
	if i < 0 || i >= snapcastState(len(_snapcastState_index)-1) {
		return "snapcastState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _snapcastState_name[_snapcastState_index[i]:_snapcastState_index[i+1]]
}
