// Code generated by "stringer -type=tvState"; DO NOT EDIT.

package regelverk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateTvOff-0]
	_ = x[stateTvOffLong-1]
	_ = x[stateTvOn-2]
}

const _tvState_name = "stateTvOffstateTvOffLongstateTvOn"

var _tvState_index = [...]uint8{0, 10, 24, 33}

func (i tvState) String() string {
	if i < 0 || i >= tvState(len(_tvState_index)-1) {
		return "tvState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tvState_name[_tvState_index[i]:_tvState_index[i+1]]
}
